### ISSUE TITLE
OnPrem: Extension only works with Inherited Customization based collections

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/azure-boards-estimate#86]
From #68:

> Thanks for the reply, it helped get further but still has issues.
> 
> After upgrading to 2019.1 OnPrem I can successfully create a session but I am unable to open it as it gives a 404 error.
> 
> ![EstimateIssue30-Aug](https://user-images.githubusercontent.com/4496632/64003640-c7bf1b00-cb60-11e9-9e5b-605cffeb2975.png)
> 
> With the network response saying that the collection does not exist:
> `{"$id":"1","innerException":null,"message":"%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentCollectionDoesNotExistException","errorCode":0,"eventId":3000}`
> 
> @cschleiden Is it possible that the extension only works for collections that are on the inheritance process model?

@TroyHouston Args, you're absolutely right, that is a scenario I did not test. I'll take a look to see if I can default to some value that makes sense if the API is not available. That could result in a (potentially) degraded experience when using XML-based customization, for example I might not be able to detect the name of the RichText field used for description on a custom work item type, but I guess that's still better than failing.

**Comment by chrismjgallant** [comment]
i'm also having this same issue after updating to Update 1. was very happy to see more progress happening but now, getting the same message as mentioned.

**Comment by cschleiden** [comment]
@chrismjgallant @TroyHouston I've pushed an update that hopefully should unblock you. 

Note: You **not** get the description for a work item if it uses a field that's not `System.Description` since there is no easy way to detect which field should be used.

**Comment by TroyHouston** [comment]
@cschleiden Unfortunately the update doesn't seem to have improved it. 
I tried creating a new session and then opening it, but I'm still getting the same errors as my previous screenshot, and the extension says that it's up to date at version 2.2.3.

I had a look at your commit, and I think the way of determining if it's a XML process or not doesn't work.

`
// Get process type id - if this is an inherited customization based project
const properties = await coreClient.getProjectProperties(project.id, ["System.ProcessTemplateType"]);
if (properties.length > 0) {
...
 } else {
// XML customization`

I checked the network calls and even though I'm using a XML process, the call to projectProperties still returns the following response:

`[{"name":"System.ProcessTemplateType","value":"6b724908-ef14-45cf-84f8-768b5384da45"}]`

**Comment by chrismjgallant** [comment]
> @chrismjgallant @TroyHouston I've pushed an update that hopefully should unblock you.
> 
> Note: You **not** get the description for a work item if it uses a field that's not `System.Description` since there is no easy way to detect which field should be used.

Hey @cschleiden, it seems like it fixed it for me! :) thanks!

**Comment by derekwalsh1** [comment]
@cschleiden @TroyHouston @chrismjgallant I'm still having the same issue myself on 2020 RC1. It's weird, I think projects that were created pre-2019 Azure DevOps Release still suffer from this problem. If I create a new Project and customize fields I have no issues. I understand that you've specified a minimum version requirement of 2019 but it seems like there is also a requirement that the project weren't created before 2019. Are you depending on a field that didn't exist in previous releases?
